### ISSUE TITLE
Request for review of VnV Plan for Image Features Detection System

### ISSUE THREAD

**Issue by Zhou4truth** [Zhou4truth/imageFeatureDetection#13]
Hi Al,
    Here is my [VnV Plan for Image Features Detection System](https://github.com/Zhou4truth/imageFeatureDetection/blob/main/docs/VnVPlan/VnV_Plan%20for%20Image%20Features%20Detection%20System.pdf).
Please give a kind review at your convenience. Thank you.
Best,
Gaofeng

**Comment by XessX** [comment]
I added #52 #53 #54 #55 issues for your VnV Plan, Thank you.

Al

**Comment by Zhou4truth** [comment]
Thanks.
