### ISSUE TITLE
VnV Section 3

### ISSUE THREAD

**Issue by vgvreug** [Zhou4truth/imageFeatureDetection#16]
- [ ] List in 3.3 should be formatted as a list, not as a paragraph
- [ ] Subsection 3.5
    - [x] #23
    - [x] #24
    - [x] #25
    - [ ] "part" is unnecessary in all three sentences.
    - [x] #26
- [x] #27
- [ ] 3.7: First word of a sentence should be capitalized and should not be "and"

**Comment by Zhou4truth** [comment]
Yes, it is GitHub copilot #23 here. and for #24 , there are several algorithms well developed already to show the perfect outcome. Here, we will use them to compare with these outcomes produced by our system. For #27, I am still working on how to apply it to this project properly. Thank you for your wonderful advice. I will look into these information  seriously.
