### ISSUE TITLE
VnV misc issues

### ISSUE THREAD

**Issue by vgvreug** [Zhou4truth/imageFeatureDetection#18]
- [ ] The extra "of Gaussian Transform" in the descriptions of DoG and LoG should be deleted. 
- [ ] The first sentence of the summary isn't relevant to summarizing the software.
- [x] #28
- [ ] Be more specific in your test outputs. Ex. For test 2, the output is the grayscale version of the input images, not any two gray images.
- [ ] In general do a second grammar check

**Comment by Zhou4truth** [comment]
Thanks. Your advice is very helpful. I will explain #28 here. Those feature points are also specified terminologies in the field of Computer Vision. So, I just kept them capitalized here.
