### ISSUE TITLE
Request for review on MG for IFDS(Image Features Detection System)

### ISSUE THREAD

**Issue by Zhou4truth** [Zhou4truth/imageFeatureDetection#20]
Hi  Valerie @vgvreug ,
   Here is my [MG documentation.](https://github.com/Zhou4truth/imageFeatureDetection/blob/main/docs/Design/SoftArchitecture/MG_for_IFDS.pdf) I appreciate your reviews on it when you are available.
Thanks and best regards,
Gaofeng

**Comment by vgvreug** [comment]
Review complete. See issues #39 #40 #41 #42 #43
