### ISSUE TITLE
Request for review on MG for IFDS(Image Features Detection System)

### ISSUE THREAD

**Issue by Zhou4truth** [Zhou4truth/imageFeatureDetection#21]
Hi Xinyu @lele0007  ,
Here is my [MG documentation.](https://github.com/Zhou4truth/imageFeatureDetection/blob/main/docs/Design/SoftArchitecture/MG_for_IFDS.pdf) I appreciate your reviews on it when you are available.
Thanks and best regards,
Gaofeng

**Comment by smiths** [comment]
@Zhou4truth you should have a separate issue assigned to me to review your MG and MIS.  One issue to review both is fine.

**Comment by Zhou4truth** [comment]
Thanks Professor, I will create a separate issue for you.> @Zhou4truth you should have a separate issue assigned to me to review your MG and MIS. One issue to review both is fine.
