### ISSUE TITLE
Request reviewing for MG for IFDS 

### ISSUE THREAD

**Issue by Zhou4truth** [Zhou4truth/imageFeatureDetection#22]
Hi Professor @smiths  ,
    Thanks for your reminding. I invite you to review the [MG documentation here.](https://github.com/Zhou4truth/imageFeatureDetection/blob/main/docs/Design/SoftArchitecture/MG_for_IFDS.pdf) I appreciate your patience and kind support.
Best regards,
Gaofeng

**Comment by smiths** [comment]
[GaofengMG_for_IFDS.pdf - PDF Expert.pdf](https://github.com/Zhou4truth/imageFeatureDetection/files/14846191/GaofengMG_for_IFDS.pdf.-.PDF.Expert.pdf)
