### ISSUE TITLE
Software Requirements Specifications___Gaofeng Zhou

### ISSUE THREAD

**Issue by Zhou4truth** [Zhou4truth/imageFeatureDetection#3]
[Software Requriement Specifications.pdf](https://github.com/Zhou4truth/imageFeatureDetection/files/14175218/Software.Requriement.Specifications.pdf)

**Comment by vgvreug** [comment]
Review complete, please see issues #4 #5 #6 #7 #8 #9

**Comment by Zhou4truth** [comment]
Thank you so much Valerie. Your advice is priceless to me. Your work is enormously appreciated here. @vgvreug

**Comment by smiths** [comment]
@Zhou4truth in the future, please create separate issues for each of your reviewers, so that they can close the issue when the review is complete.

**Comment by smiths** [comment]
@Zhou4truth your secondary reviewer for the SRS was supposed to be Mousavi, Seyed Ali (alimousavi1997)

**Comment by smiths** [comment]
The feedback is attached.  You may wish to create issues from the feedback to organize your work and clearly show the changes between the current version and the final version.  The grade will be posted on Avenue soon.

[GaofengZhou_SRS.pdf](https://github.com/Zhou4truth/imageFeatureDetection/files/14390143/GaofengZhou_SRS.pdf)

**Comment by alimousavi1997** [comment]
[SRS_Zhou_review.pdf](https://github.com/Zhou4truth/imageFeatureDetection/files/14394824/SRS_Zhou_review.pdf)
Review for your SRS doc
