### ISSUE TITLE
(MG) About AC4 and UC3

### ISSUE THREAD

**Issue by lele0007** [Zhou4truth/imageFeatureDetection#30]
AC4: The way to display the outcomes depending on different OS platform.
  UC3: The layout of GUI is kept unchanged.
  Do AC4 and UC3 conflict since as shown in Figure 2, the output image will also be displayed in a box in the UI?

**Comment by Zhou4truth** [comment]
Thanks. Here I mean the dimensions will change depending on different platforms, but not the layout about the GUI such as where those buttons or windows will be settled.
