### ISSUE TITLE
(MG) Problems about section 7.3.1

### ISSUE THREAD

**Issue by lele0007** [Zhou4truth/imageFeatureDetection#33]
In section 7.3.1, it should include “Secrets, Services, Implemented By, and Type of Module” of other Software Decision Modules, not just Etc.

**Comment by Zhou4truth** [comment]
Thanks for reminding me on this. However, as I meant to make this software open sourced including all those algorithms or implementing methods. So, I think it would be unnecessary to add this part into this documentation.

**Comment by vgvreug** [comment]
Seconding this issue and issue #32. If anything, if you want to make this open source it might be more important to have a thorough module guide so people understand the design of the software before changing it.
