### ISSUE TITLE
(MG) Problems about Figure 1 : Use hierarchy among modules

### ISSUE THREAD

**Issue by lele0007** [Zhou4truth/imageFeatureDetection#35]
In Table3, it said that there is a trace between AC4 (display the outcomes) and M3(Control Module)., but in Figure 1, there is no connection between the control module and the output module.

**Comment by Zhou4truth** [comment]
> In Table3, it said that there is a trace between AC4 (display the outcomes) and M3(Control Module)., but in Figure 1, there is no connection between the control module and the output module.

Thanks for this question. In this workflow, after we clicked one button using the control module, then there would be an output displayed automatically after be processed by those algorithms under going. So here, the control flow will give commands through the control module, and then there would some processing work in the algorithm part, and then it would come to the output display. So, that means a indirect control flow there.
