### ISSUE TITLE
Request for reviewing for MIS 

### ISSUE THREAD

**Issue by Zhou4truth** [Zhou4truth/imageFeatureDetection#36]
Hi Professor Spencer, 
     Here is the [MIS](https://github.com/Zhou4truth/imageFeatureDetection/blob/main/docs/Design/SoftDetailedDes/MIS_for_IFDS.pdf)document. I appreciate your review on this very much.   
    Thanks and best regards,
Gaofeng

**Comment by smiths** [comment]
[GaofengMIS_for_IFDS.pdf - PDF Expert.pdf](https://github.com/Zhou4truth/imageFeatureDetection/files/14846194/GaofengMIS_for_IFDS.pdf.-.PDF.Expert.pdf)
