### ISSUE TITLE
Request for Review on MIS for IFDS

### ISSUE THREAD

**Issue by Zhou4truth** [Zhou4truth/imageFeatureDetection#37]
Hi Valerie,
Here is my [MIS](https://github.com/Zhou4truth/imageFeatureDetection/blob/main/docs/Design/SoftDetailedDes/MIS_for_IFDS.pdf)document. I appreciate your review on this very much.
Thanks and best regards,
Gaofeng

**Comment by vgvreug** [comment]
Review complete. See #44 #45 #46 #47 #48
