### ISSUE TITLE
SRS not in github

### ISSUE THREAD

**Issue by vgvreug** [Zhou4truth/imageFeatureDetection#4]
I can access your SRS through issue #3 , but it doesn't seem to have been updated in github.

**Comment by vgvreug** [comment]
I looked again and I did find the pdf, but for the ease of whoever is reviewing your documents you should upload files under the name they're expecting and include the .tex file as well.

**Comment by Zhou4truth** [comment]
Sorry, I should have added the link here.> I looked again and I did find the pdf, but for the ease of whoever is reviewing your documents you should upload files under the name they're expecting and include the .tex file as well.
