### ISSUE TITLE
MIS: misc issues

### ISSUE THREAD

**Issue by vgvreug** [Zhou4truth/imageFeatureDetection#48]
- [x] There appears to be a double space in the title between "for" and "IDFS"
- [x] Section 3: space in the wrong spot near first link
- [x] Formatting issue in Table 1: see #42 
- [x] 6.4.3: Appears to be an improperly formatted comment

**Comment by Zhou4truth** [comment]
Thank you so much, Valerie, I have corrected them in the new version.
