### ISSUE TITLE
Issue 2: Incomplete Test Descriptions

### ISSUE THREAD

**Issue by XessX** [Zhou4truth/imageFeatureDetection#53]
Test descriptions in Section 4.1 (Tests for Functional Requirements) lack detailed inputs, expected outputs, and specific conditions.
You can expand test descriptions to include detailed inputs, expected outputs, and conditions.
Location: Section 4.1, particularly tests 4.1.1 to 4.1.5.

**Comment by Zhou4truth** [comment]
Thanks. The GUI can show the visual display of feature points which is the output. Yeah. I should make it clearer.
