### ISSUE TITLE
Misc. issues from first two sections

### ISSUE THREAD

**Issue by vgvreug** [Zhou4truth/imageFeatureDetection#9]
- Sec 1.1 
   - The descriptions of DoG and LoG appear to be incomplete
   - Adding a blank line between the text and the chart would help readability
- Sec 2
   - Missing space after comma between "words" and "computer vision"
   - "in another words" -> "in other words"
   - "Especially" should probably be "It is particularly important" or a similar phrase
   - No comma after "Especially" and lowercase "W" in "When"
   - Sec 2.2
      - Sentences should not start with "And" 
      - Second sentence "We" should not be capitalized.
      - Fourth sentence, I assume the period was meant to be a comma.
- General issues
   - Unless they are in a list, sentences should generally be formatted as paragraphs instead of each one being on a separate line.

You might want to make a point of doing a slow, careful read through of your documentation before submitting to check for grammar and formatting issues.

**Comment by Zhou4truth** [comment]
Thank you so much for your time. It's so detailed.
